# Generated by Django 5.2.11 on 2026-02-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_vote_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='candidate',
        ),
        migrations.AddField(
            model_name='vote',
            name='encrypted_candidate',
            field=models.TextField(default='old_vote'),
            preserve_default=False,
        ),
    ]
