# Generated by Django 5.2.10 on 2026-01-24 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_voter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_faces', models.IntegerField(default=1)),
                ('vote_time_limit', models.IntegerField(default=120, help_text='Seconds')),
            ],
        ),
        migrations.CreateModel(
            name='ProctoringLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('NO_FACE', 'No Face Detected'), ('MULTIPLE_FACES', 'Multiple Faces Detected'), ('CAMERA_OFF', 'Camera Tampering'), ('FACE_CHANGED', 'Face Changed'), ('TIME_EXCEEDED', 'Time Exceeded')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.BooleanField(default=False)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.voter')),
            ],
        ),
    ]
