# Generated by Django 5.2.10 on 2026-01-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proctoringrule',
            name='max_faces',
        ),
        migrations.AddField(
            model_name='proctoringrule',
            name='max_warnings',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='proctoringrule',
            name='vote_time_limit',
            field=models.IntegerField(default=120),
        ),
    ]
