# Generated by Django 5.2.10 on 2026-01-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_voter_face_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
