# Generated by Django 5.2.10 on 2026-01-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_candidate_id_alter_election_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='vote_time_limit',
            field=models.IntegerField(default=120, help_text='Voting time limit in seconds'),
        ),
    ]
